<?php

use App\Model\Products\Product;
use Illuminate\Database\Seeder;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = [

            array(
                'id' => '1',
                'name' => 'T-Shirt',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'stock' => '5',
                'active' => '1',
                'description' => 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.you will receive an instance of Illuminate\Pagination\Paginator. These objects provide several methods that describe the result ',
                'unit_price' => '0.00',
                'credit_price' => '0.00',
                'quantity' => '20',
                'avatar' => 'men-t-shirt-tupac.jpeg',
                'created_at' => '2020-02-25 00:00:00',
                'updated_at' => '2020-02-25 00:00:00',
            ),

            array(
                'id' => '2',
                'name' => 'T Shirt',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'active' => '1',
                'description' => 'men t shirt bob marley',
                'unit_price' => '0.00',
                'credit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => 'men-t-shirt-bob-marley.jpeg',
                'created_at' => '2020-02-25 00:00:00',
                'updated_at' => '2020-02-25 00:00:00',
            ),
            array(
                'id' => '3',
                'name' => 't shirt',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'men t-shirt bob marley white',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => 'men-t-shirt-bob-marley-white.jpeg',
                'created_at' => '2020-02-25 00:00:00',
                'updated_at' => '2020-02-25 00:00:00',
            ),

            array(
                'id' => '4',
                'name' => 't shirt',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'men T-shirt with tupac drawing',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => 'men-t-shirt-tupac-white.jpeg',
                'created_at' => '2020-02-25 00:00:00',
                'updated_at' => '2020-02-25 00:00:00',

            ),

            array(
                'id' => '5',
                'name' => 'T Shirt',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'active' => '1',
                'description' => 'men t shirt with tupac picture',
                'unit_price' => '0.00',
                'credit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => 'men-t-shirt-tupac-pic.jpeg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '6',
                'name' => 'T Shirt',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'ladies t shirt with tupac picture',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => 'led-t-shirt.jpeg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '7',
                'name' => 'Fashion Jeans',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'laddies design jeans',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => 'ledies-skinny.jpeg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '8',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'extrem design - laddies trousers',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => 'leddies-trouse.jpeg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '9',
                'name' => 'lingerie',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero's De Finibus Bonorum et Malorum for use in a type specimen book.",
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '1.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '38',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero's De Finibus Bonorum et Malorum for use in a type specimen book.",
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '20.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '10',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero's De Finibus Bonorum et Malorum for use in a type specimen book.",
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '3.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '11',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero's De Finibus Bonorum et Malorum for use in a type specimen book.",
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '4.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '12',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero's De Finibus Bonorum et Malorum for use in a type specimen book.",
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '5.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '13',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero's De Finibus Bonorum et Malorum for use in a type specimen book.",
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '6.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '14',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'store_id' => '1',
                 'brand_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'extrem design - laddies trousers',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '7.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '15',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'extrem design - laddies trousers',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '8.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '16',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'store_id' => '1',
                 'brand_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'extrem design - laddies trousers',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '9.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '17',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'extrem design - laddies trousers',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '10.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '18',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'extrem design - laddies trousers',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '11.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '19',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'extrem design - laddies trousers',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '12.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '20',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'extrem design - laddies trousers',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '13.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '21',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'extrem design - laddies trousers',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '14.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '22',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'extrem design - laddies trousers',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '15.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '23',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'extrem design - laddies trousers',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '15.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '24',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'extrem design - laddies trousers',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '16.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '25',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'extrem design - laddies trousers',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '17.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '26',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'extrem design - laddies trousers',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '18.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '27',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'extrem design - laddies trousers',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '19.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '28',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'extrem design - laddies trousers',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '20.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '29',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'extrem design - laddies trousers',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '21.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '30',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'extrem design - laddies trousers',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '22.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '31',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'extrem design - laddies trousers',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '23.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '32',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'extrem design - laddies trousers',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '24.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '33',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'extrem design - laddies trousers',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '25.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '34',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'extrem design - laddies trousers',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '26.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '35',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'extrem design - laddies trousers',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '27.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '36',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'extrem design - laddies trousers',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '28.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),
            array(
                'id' => '37',
                'name' => 'Trouses',
                'size' => '8',
                'color_id' => '1',
                'brand_id' => '1',
                'store_id' => '1',
                'licensor_id' => '1',
                'sku' => 'sku100',
                'credit_price' => '0.00',
                'active' => '1',
                'description' => 'extrem design - laddies trousers',
                'unit_price' => '0.00',
                'quantity' => '20',
                'store_id' => '1',
                'stock' => '5',
                'avatar' => '30.jpg',
                'created_at' => '2020-08-05 00:00:00',
                'updated_at' => '2020-08-05 00:00:00',
            ),

        ];
        foreach ($products as $product) {
            Product::create($product);
        }
    }
}